name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
        #python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-22.04]
        #os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
  ci-all:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - run: |
          echo "All matrix jobs have completed successfully!"
  release:
    if: github.event_name == 'push'
    needs: ci-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get Tag
        uses: devops-actions/action-get-tag@v1.0.3
        id: tag
        with:
          strip_v: true
          default: v0.0.1
      - name: Create release
        id: create_release
        uses: comnoco/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release
            - Not much
          draft: false
          prerelease: false
      

    
