name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
  ci-all:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - run: |
          echo "All matrix jobs have completed successfully!"
  release:
    if: github.event_name == 'push'
    needs: ci-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> GITHUB_TAGS_OUTPUT
      - name: Check output
        env: 
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag"
