name: CI
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
        #python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-22.04]
        #os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
  ci-all:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - run: |
          echo "All matrix jobs have completed successfully!"
  release:
#    if: startsWith(github.ref ,'refs/tags/')
    needs: ci-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check ref
        run: |
          echo "tag_name: ${{ github.ref }}"
    
